### ISSUE TITLE
mkq-mr1 branch repo sync error

### ISSUE THREAD

**Issue by BlankShrimp** [MoKee/android#18]
```
Checking out projects:  37% (280/755) platform/external/plyerror: 
Cannot checkout platform/external/protobuf-javalite: ManifestInvalidRevisionError: revision refs/tags/android-10.0.0_r23 in platform/external/protobuf-javalite not found   
error: in `sync`: revision refs/tags/android-10.0.0_r23 in platform/external/protobuf-javalite not found
```

**Comment by martincz** [comment]
https://github.com/MoKee/android/blob/mkq-mr1/default.xml#L297
platform/external/protobuf-javalite is fetch from AOSP remote.

```
  <remote  name="aosp"
           fetch="https://android.googlesource.com"
           review="android-review.googlesource.com"
           revision="refs/tags/android-10.0.0_r23" />
```

If you sync repos via a third mirror, please check it or switch to aosp default.

**Comment by BlankShrimp** [comment]
> https://github.com/MoKee/android/blob/mkq-mr1/default.xml#L297
> platform/external/protobuf-javalite is fetch from AOSP remote.
> 
> ```
>   <remote  name="aosp"
>            fetch="https://android.googlesource.com"
>            review="android-review.googlesource.com"
>            revision="refs/tags/android-10.0.0_r23" />
> ```
> 
> If you sync repos via a third mirror, please check it or switch to aosp default.

![image](https://user-images.githubusercontent.com/35521976/73480544-08071b80-43d5-11ea-9885-c65915d527da.png)
Seems correct but doesn't work.
