### ISSUE TITLE
Manifest: Marshmallow (mkm) Branch

### ISSUE THREAD

**Issue by dgadelha** [MoKee/android#5]
The `mkm` branch is missing.

**Comment by martincz** [comment]
Look like you are a device maintainer. You can register MoKee Code Review.
https://review.mfunz.com/
Tell me your account name, I'll add into Device Maintainers group.
Then, you can sync mkm branch source code.

**Comment by dgadelha** [comment]
Hi @martincz,
- Personal information removed.
  Thanks!

**Comment by martincz** [comment]
Now you can sync code from here: https://review.mfunz.com/#/admin/projects/MoKee/android (Please use ssh protocol)
If you want create a new repository just tell me repository name.
For example:
android_device_xx_xx
android_kernel_xx_xx
android_vendor_xx_xx
Repository name should all lowercase letters.
I'll create them and grant owner permission for you.

**Comment by dgadelha** [comment]
I've sent you an email.
Thanks!

**Comment by XperiAMM** [comment]
Hi, MKM would compile for the device jagnm, i am register MoKee Code Review https://review.mfunz.com/.


User: XperiAMM
email: andresmora1676@gmail.com

**Comment by Nothing-Dev** [comment]
Hi @martincz.
My username is NV-Dev and my email is alfredomartinez1423@gmail.com.
Very Thanks!

**Comment by linhphi9x94** [comment]
Hi @martincz.
My username is LinhPHi and my email is linhphi9x94@gmail.com.
I hope  you add into Device Maintainers group
Very Thanks!

**Comment by Ryuinferno** [comment]
Guys, stop posting your email and details here. The issue is closed and will not be attended to. If you want to apply as a device maintainer, go here instead http://www.mokeedev.com/en/developer-application/

**Comment by Bauuuuu** [comment]
And nobody replies to those applications ??? .its been more than a week i applied and wrote email to 
thats my username "Bauuuuu" on https://review.mfunz.com/

**Comment by Brooklyn2001** [comment]
Hi @martincz,
My email is brooklyn2001@gmail.com.
I wont sync mkm code.
Thanks

**Comment by quick163** [comment]
Hi @martincz,
My email is vasifok@gmail.com
I wont sync mkm code.
Very Thanks!

**Comment by Bauuuuu** [comment]
Issue is closed just port the rom.. as i did ))

**Comment by jxdqwer** [comment]
Hi @martincz,
My email is qwer768688093@outlook.com
I wont sync mkm code.
Thank you
