### ISSUE TITLE
MKM source code access

### ISSUE THREAD

**Issue by Bauuuuu** [MoKee/android#8]

**Comment by Ryuinferno** [comment]
There is no promise that every single application will be replied to, only approved ones. We do not need people to build from a existing/slightly modified device tree, we need people who can do more than that (device bring up from scratch, significant commits towards device tree etc). Based on the proof you submitted, unfortunately you didn't meet the requirements.

**Comment by Bauuuuu** [comment]
but does that means i would never get the mokee for Nubia Z9 Max nx512j ? Apparently, i am the only one who has been compiling for this device and updating device tree for this phone.... although you may consider not enough commits ... but hey i am just starting for this device. i hope you consider to give me access to the mkm source code.

**Comment by Lorenz15** [comment]
I want to build Mokee Marshmallow for Sony Xperia L(taoshan) too...I want to build it unofficial, but I need access to the mkm source code too...

**Comment by Bauuuuu** [comment]
mokee people please consider our request .. please please

**Comment by Bauuuuu** [comment]
Mokee doesnt need people even if their information says "newcomers are always welcome" its not cool to reject the applications of people who are actively willing to participate....  I am closing this issue its pointless to keep it open gud luck mokee with closed source...

**Comment by Bauuuuu** [comment]
closing for above comment...
